all:np_simple.cpp np_single_proc.cpp np_multi_proc.cpp
	g++ np_simple.cpp -o np_simple
	g++ np_single_proc.cpp -o np_single_proc
	g++ np_multi_proc.cpp -o np_multi_proc -lrt  
clean:
	rm -f np_simple np_single_proc np_multi_proc
